### ISSUE TITLE
None of the plant growing machines work with the Red Orchid

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#104]
After significant testing with player Starwarsman1, we’d discovered that absolutely none of the plant growing machines (plant interactive, grower, sower, mechanical user with any type of tool or empty in any mode, block breaker) allow for harvesting of Red Orchids. 

We have worked out a single way to do it using blow updates or timers and a vanilla piston with a mechanical user placing the new Red Orchid. This can generate about 1 Redstone every 5 seconds with Growth Crystals  maxed out (18 or so tier 3)

Photos of the machines not working and of the work around are available on request.

**Comment by SuperFurias** [comment]
Well you have not tried everything, dear, there is the Plant Interactor (which I am currently using as well, and interacts with the Red Orchid) the only negative thing is that the redstone is the drop on the ground. you will need a vacuum hopper or something like that. There is no need to replant the Red Orchid, the Plant Interactor simulates the "right button" on any plant that you put it, since the harvest mod almost all plants can be harvested with the right button, so this machine is OP

**Comment by SuperFurias** [comment]
A question, are you Italian? it is clear from the self-correction of the google translator (I am also Italian)

**Comment by Next-victim** [comment]
Issue solved. Fake player status was set to "ally" instead of "member". Could we get a pin about this in the server room in discord? It was confusing for ages.

Closed.
