### ISSUE TITLE
No way to get Rubidium or Green Antimatter

### ISSUE THREAD

**Issue by Keltas** [al132mc/antimatter-chemistry#20]
I wanted to fulfill the quest for 64 green antimatter however according to JEI it requires rubidium to make and according to JEI the only source of rubidium is green antimatter. As such I am unable to get either. Am I missing something obvious, or is there some source of one of those materials? Right now I am stuck at this quest.

**Comment by al132mc** [comment]
JEI (Should?) also indiciate that you can get Rubidium from loot crates ,which you can get by killing mobs in the nether. In any case, I will keep this issue open as a personal reminder to add a tooltip to rubidium and/or specifying in the quest how to acquire it, because this is one of the most frequent areas where people seem to get stuck.

**Comment by Keltas** [comment]
You are right of course. I didn't notice the lootcrates. Thank you for swift reply!

**Comment by al132mc** [comment]
I added a description to the quest, so hopefully others have an easier time figuring it out in the future.
