### ISSUE TITLE
"End cities are disabled" but aren't

### ISSUE THREAD

**Issue by BinaryEnigma01** [al132mc/antimatter-chemistry#228]
Likely just for servers but end cities are certainly not disabled here, made the quest real easy.

**Comment by ghost** [comment]
Odd, but not a problem. They weren't intentionally disabled in the first place, so I don't really see this as a big deal. The default world save has the spawnstructures gamerule disabled because I wanted to make sure that villages and the like weren't generated, but it unintentionally disabled end cities. Once I found this out I decided to just keep it as is. Whether or not they spawn, it's fine.
