### ISSUE TITLE
All RFTools Dimensions have Mining Fatigue 3, Poison 3, Hunger 3, and Slowness 3

### ISSUE THREAD

**Issue by TroubledPlays** [al132mc/antimatter-chemistry#259]
All of the dimensions I have been too have the effects listed above. Even with the Effect (none) dimlet included

**Comment by Wishbone1977** [comment]
To the best of my knowledge, this is always the case if your dimension has less than 4 million RF. The negative effects are a warning to charge up your dimension before it collapses. Try charging up your dimensions more, and keep an eye on how much energy they have left. Keep in mind that some dimlets have fairly outrageous energy requirements. The dimension I made for mining dimensional shards (huge orbs of dimensional shard ore) uses more than 18,000 RF/tick. Also, be sure to put down an activity probe inside each dimension. This ensures that the dimension does not use any energy when you are not in it. Otherwise, the energy will drain from it constantly.

**Comment by pwaksman973** [comment]
I get the idea here, but, would ne nice if those effects show up only if you are actually losing power. Having a dimension that cost 18RF/t gaining 200RF/t, means it will never collapse, but you still can't go there cause you have to wait ..... kind link boring. Maybe a config option to only have debuffs if the power is decreasing would help...

Or if the shield actually prevent you for taking those debuffs. It help you go to a unpowered dimension, but can't help in a powered one...

**Comment by OniyaMCD** [comment]
First, make a Dimension Editor (yes, you need another emerald for that.)  Then craft the 'Effect None' dimlet, with 3 paper, 3 redstone, and an apple. (The redstone makes a tent over the apple, paper across the bottom.)  Take your bad-effect dimension, and put it in the left slot of the Editor.  Put the 'Effect None' dimlet in the right slot.  Presto!  Dimension that doesn't wither you to death!
