### ISSUE TITLE
Thermal Expansion tank doesn't display fluid level

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#37]
Thermal Expansion tank (basic) doesn't visually display fluid level when looked at. Does display level in "The One Probe". Screenshot included at the bottom.

I'm not 100% sure if this is a pack issue or a Thermal Expansion issue.

![Example where TOP says 12.8 buckets of 20 but the actual tank appears full](https://user-images.githubusercontent.com/51034324/58375043-2f3d4d00-7f18-11e9-985f-6d6926077aea.png)

**Comment by al132mc** [comment]
I think this was actually just fixed in Thermal Expansion today. The changelog says the following

`
CHANGELOG
====================================================================================================
5.5.4:
----------------------------------------------------------------------------------------------------

GENERAL:
	-Localization! Also fixes a couple of minor issues such as tank rendering.
`

I will close this issue when I update the mod and confirm it works

**Comment by al132mc** [comment]
Should be fixed in 1.2.0
