### ISSUE TITLE
Antimatter in Chemical Disolver

### ISSUE THREAD

**Issue by Middelin** [al132mc/antimatter-chemistry#5]
This might be intentional, but I wanted to mention it just in case. Whenever you place multiple pieces of antimatter into the chemical dissolver, it only outputs five silicon dioxide instead of the normal outputs

**Comment by al132mc** [comment]
Yes, I just was made aware of this. It's definitely not intentional. The short version is that Antimatter is only renamed concrete, and in the most recent version of Alchemistry I added default Dissolver recipes for Concrete that give 5 silicon dioxide, so there is a recipe clash. I am uploading a new version of the pack right now that will fix this.

**Comment by al132mc** [comment]
v0.4.14 is up, this should be fixed.
