### ISSUE TITLE
Quests messed up after updating to 1.2.8

### ISSUE THREAD

**Issue by Fsbn1** [al132mc/antimatter-chemistry#88]
Quests messed up after updating to 1.2.8

Screens -> https://imgur.com/a/LXAsrd6

**Comment by al132mc** [comment]
I had to modify 2 of the quests because they had the wrong requirements (should have been 8x required the pristine zombie matter quest, rather than 1) Once you complete this quest again, progress will jump back to wherever it should be. If you are playing single player you can either just acquire these items again, or use the command ``/ftbquests editing_mode``, then right-click the quest that should already be finished and select "complete instantly"

I apologize for the inconvenience. Please comment if you are unable to figure this out
